"""
Core message and role types for the tool-calling library.

These primitives are provider-agnostic and are reused across adapters,
the agent loop, and tests.
"""

from __future__ import annotations

import base64
from dataclasses import dataclass, field
from enum import Enum
from pathlib import Path
from typing import Any, Dict, List, Optional, Protocol

from selectools.stability import stable


@stable
class Role(str, Enum):
    """
    Enumeration of conversation roles for messages.

    Attributes:
        USER: Message from the end user or customer.
        ASSISTANT: Message generated by the AI assistant/agent.
        SYSTEM: System-level instruction or prompt (typically used for agent configuration).
        TOOL: Message containing the result of a tool execution.
    """

    USER = "user"
    ASSISTANT = "assistant"
    SYSTEM = "system"
    TOOL = "tool"


def _encode_image(image_path: str) -> str:
    """Load and base64-encode an image from disk."""
    path = Path(image_path).expanduser().resolve()
    if not path.exists():
        raise FileNotFoundError(f"Image file not found: {path}")

    data = path.read_bytes()
    return base64.b64encode(data).decode("utf-8")


@stable
@dataclass
class ContentPart:
    """A single part of a multimodal message (text, image, etc.).

    Use this to build messages with multiple images or mixed content types.

    Example:
        >>> parts = [
        ...     ContentPart(type="text", text="What's in these images?"),
        ...     ContentPart(type="image_url", image_url="https://example.com/photo.jpg"),
        ...     ContentPart(type="image_base64", image_base64="...", media_type="image/png"),
        ... ]
        >>> msg = Message(role=Role.USER, content="", content_parts=parts)
    """

    type: str  # "text", "image_url", "image_base64"
    text: Optional[str] = None
    image_url: Optional[str] = None
    image_base64: Optional[str] = None
    media_type: Optional[str] = None  # "image/png", "image/jpeg", etc.


def image_message(image: str, prompt: str = "Describe this image.") -> "Message":
    """Create a user message with an image.

    Args:
        image: URL (http/https) or local file path.
        prompt: Text prompt to accompany the image.

    Returns:
        A Message with content_parts containing the text and image.
    """
    parts: List[ContentPart] = [ContentPart(type="text", text=prompt)]
    if image.startswith(("http://", "https://")):
        parts.append(ContentPart(type="image_url", image_url=image))
    else:
        b64 = _encode_image(image)
        suffix = Path(image).suffix.lower()
        media = {
            "png": "image/png",
            "jpg": "image/jpeg",
            "jpeg": "image/jpeg",
            "gif": "image/gif",
            "webp": "image/webp",
        }.get(suffix.lstrip("."), "image/jpeg")
        parts.append(ContentPart(type="image_base64", image_base64=b64, media_type=media))
    msg = object.__new__(Message)
    msg.role = Role.USER
    msg.content = prompt
    msg.content_parts = parts
    msg.image_path = None
    msg.image_base64 = None
    msg.tool_name = None
    msg.tool_result = None
    msg.tool_calls = None
    msg.tool_call_id = None
    return msg


def text_content(message: "Message") -> str:
    """Extract text content from a Message, handling both str and content_parts."""
    if message.content_parts:
        return (
            " ".join(p.text for p in message.content_parts if p.type == "text" and p.text)
            or message.content
            or ""
        )
    return message.content or ""


@stable
@dataclass
class Message:
    """
    Conversation message with optional inline image payload and tool metadata.

    The `image_base64` field is populated automatically when `image_path` is
    provided so adapters can forward vision content to providers without
    re-encoding.

    Attributes:
        role: The role of the message sender (USER, ASSISTANT, SYSTEM, or TOOL).
        content: The text content of the message.
        image_path: Optional path to an image file for vision-enabled models.
                    The image will be automatically base64-encoded on initialization.
        tool_name: Optional name of the tool that generated this message (for TOOL role).
        tool_result: Optional result from tool execution (for TOOL role).
        image_base64: Auto-populated base64-encoded image data (not set via __init__).

    Example:
        >>> # Simple user message
        >>> msg = Message(role=Role.USER, content="Hello!")
        >>>
        >>> # Message with image for vision models
        >>> msg = Message(
        ...     role=Role.USER,
        ...     content="What's in this image?",
        ...     image_path="./photo.jpg"
        ... )
        >>>
        >>> # Tool result message
        >>> msg = Message(
        ...     role=Role.TOOL,
        ...     content="Weather is 72°F and sunny",
        ...     tool_name="get_weather"
        ... )
    """

    role: Role
    content: str = ""
    image_path: Optional[str] = None
    tool_name: Optional[str] = None
    tool_result: Optional[str] = None
    tool_calls: Optional[List["ToolCall"]] = None
    tool_call_id: Optional[str] = None
    content_parts: Optional[List[ContentPart]] = None
    image_base64: Optional[str] = field(init=False, default=None)

    def __post_init__(self) -> None:
        """Automatically encode image if image_path is provided."""
        if self.image_path:
            self.image_base64 = _encode_image(self.image_path)

    def to_dict(self) -> Dict[str, Any]:
        """
        Return a plain-JSON-safe representation for logging or debugging.

        Returns:
            Dictionary containing all message fields with the role converted to its string value.
        """
        return {
            "role": self.role.value,
            "content": self.content,
            "image_base64": self.image_base64,
            "tool_name": self.tool_name,
            "tool_result": self.tool_result,
            "tool_calls": (
                [
                    {
                        "name": tc.tool_name,
                        "parameters": tc.parameters,
                        "id": tc.id,
                        "thought_signature": tc.thought_signature,
                    }
                    for tc in self.tool_calls
                ]
                if self.tool_calls
                else None
            ),
            "tool_call_id": self.tool_call_id,
        }

    @classmethod
    def from_dict(cls, data: Dict[str, Any]) -> "Message":
        """Reconstruct a Message from a dictionary produced by to_dict().

        Uses ``object.__new__`` to skip ``__post_init__`` so stale
        ``image_path`` values are never re-encoded.  The persisted
        ``image_base64`` is restored directly instead.
        """
        msg = object.__new__(cls)
        msg.role = Role(data["role"])
        msg.content = data.get("content", "")
        msg.image_path = None
        msg.image_base64 = data.get("image_base64")
        msg.tool_name = data.get("tool_name")
        msg.tool_result = data.get("tool_result")
        msg.tool_call_id = data.get("tool_call_id")
        raw_calls = data.get("tool_calls")
        if raw_calls:
            msg.tool_calls = [
                ToolCall(
                    tool_name=tc["name"],
                    parameters=tc.get("parameters", {}),
                    id=tc.get("id"),
                    thought_signature=tc.get("thought_signature"),
                )
                for tc in raw_calls
            ]
        else:
            msg.tool_calls = None
        return msg


@stable
@dataclass
class ToolCall:
    """
    Structured representation of a parsed tool call from an LLM response.

    This class represents the agent's decision to invoke a specific tool
    with given parameters. It's typically extracted from the LLM's response
    text by a ToolCallParser.

    Attributes:
        tool_name: Name of the tool to invoke (must match a registered tool).
        parameters: Dictionary mapping parameter names to their values for tool execution.

    Example:
        >>> tool_call = ToolCall(
        ...     tool_name="get_weather",
        ...     parameters={"location": "San Francisco", "units": "celsius"}
        ... )
    """

    tool_name: str
    parameters: Dict[str, Any]
    id: Optional[str] = None
    thought_signature: Optional[str] = None


@stable
@dataclass
class AgentResult:
    """
    Structured result from an agent run.

    Wraps the final assistant response with metadata about which tools were
    called and how many iterations the agent used. Provides backward-compatible
    `content` and `role` properties so existing code that accesses
    ``result.content`` continues to work.

    Attributes:
        message: The final assistant response message.
        tool_name: Name of the last tool called, or None if no tool was used.
        tool_args: Parameters passed to the last tool call.
        iterations: Number of loop iterations used.
        tool_calls: Ordered list of all tool calls made during the run.
        parsed: Validated structured output when ``response_format`` was used.
        reasoning: LLM reasoning text accompanying the final tool selection.
        reasoning_history: Reasoning text from each iteration that selected a tool.
        trace: Execution trace capturing every step of the agent run.
        provider_used: Name of the provider that handled the run (useful with FallbackProvider).

    Example:
        >>> result = agent.run([Message(role=Role.USER, content="Search for Python")])
        >>> result.content          # backward-compatible
        'Here are the results...'
        >>> result.tool_name        # structured access
        'search_web'
        >>> result.tool_args
        {'query': 'Python'}
        >>> result.iterations
        2
    """

    message: Message
    tool_name: Optional[str] = None
    tool_args: Dict[str, Any] = field(default_factory=dict)
    iterations: int = 0
    tool_calls: List["ToolCall"] = field(default_factory=list)
    parsed: Optional[Any] = None
    reasoning: Optional[str] = None
    reasoning_history: List[str] = field(default_factory=list)
    trace: Optional[Any] = None
    provider_used: Optional[str] = None
    usage: Optional[Any] = None

    @property
    def content(self) -> str:
        """Backward-compatible access to the final response text."""
        return self.message.content

    @property
    def role(self) -> "Role":
        """Backward-compatible access to the message role."""
        return self.message.role


@dataclass
class StreamChunk:
    """
    A chunk of streaming content from the agent.

    Attributes:
        content: The text content of this chunk (delta).
        role: The role emitting this chunk (usually ASSISTANT).
        tool_calls: Optional list of tool calls (if this chunk contains tool invocations).
    """

    content: str = ""
    role: Role = Role.ASSISTANT
    tool_calls: Optional[List[ToolCall]] = None


class StreamHandler(Protocol):
    """Protocol for handling streaming response chunks."""

    async def on_chunk(self, chunk: StreamChunk) -> None:
        """Called when a new chunk of content is available."""
        ...


__all__ = ["Role", "Message", "ToolCall", "AgentResult", "StreamChunk", "StreamHandler"]
