"""
Core message and role types for the tool-calling library.

These primitives are provider-agnostic and are reused across adapters,
the agent loop, and tests.
"""

from __future__ import annotations

import base64
from dataclasses import dataclass, field
from enum import Enum
from pathlib import Path
from typing import Any, Dict, List, Optional


class Role(str, Enum):
    """
    Enumeration of conversation roles for messages.

    Attributes:
        USER: Message from the end user or customer.
        ASSISTANT: Message generated by the AI assistant/agent.
        SYSTEM: System-level instruction or prompt (typically used for agent configuration).
        TOOL: Message containing the result of a tool execution.
    """

    USER = "user"
    ASSISTANT = "assistant"
    SYSTEM = "system"
    TOOL = "tool"


def _encode_image(image_path: str) -> str:
    """Load and base64-encode an image from disk."""
    path = Path(image_path).expanduser().resolve()
    if not path.exists():
        raise FileNotFoundError(f"Image file not found: {path}")

    data = path.read_bytes()
    return base64.b64encode(data).decode("utf-8")


@dataclass
class Message:
    """
    Conversation message with optional inline image payload and tool metadata.

    The `image_base64` field is populated automatically when `image_path` is
    provided so adapters can forward vision content to providers without
    re-encoding.

    Attributes:
        role: The role of the message sender (USER, ASSISTANT, SYSTEM, or TOOL).
        content: The text content of the message.
        image_path: Optional path to an image file for vision-enabled models.
                    The image will be automatically base64-encoded on initialization.
        tool_name: Optional name of the tool that generated this message (for TOOL role).
        tool_result: Optional result from tool execution (for TOOL role).
        image_base64: Auto-populated base64-encoded image data (not set via __init__).

    Example:
        >>> # Simple user message
        >>> msg = Message(role=Role.USER, content="Hello!")
        >>>
        >>> # Message with image for vision models
        >>> msg = Message(
        ...     role=Role.USER,
        ...     content="What's in this image?",
        ...     image_path="./photo.jpg"
        ... )
        >>>
        >>> # Tool result message
        >>> msg = Message(
        ...     role=Role.TOOL,
        ...     content="Weather is 72°F and sunny",
        ...     tool_name="get_weather"
        ... )
    """

    role: Role
    content: str
    image_path: Optional[str] = None
    tool_name: Optional[str] = None
    tool_result: Optional[str] = None
    tool_calls: Optional[List["ToolCall"]] = None
    tool_call_id: Optional[str] = None
    image_base64: Optional[str] = field(init=False, default=None)

    def __post_init__(self) -> None:
        """Automatically encode image if image_path is provided."""
        if self.image_path:
            self.image_base64 = _encode_image(self.image_path)

    def to_dict(self) -> Dict[str, Any]:
        """
        Return a plain-JSON-safe representation for logging or debugging.

        Returns:
            Dictionary containing all message fields with the role converted to its string value.
        """
        return {
            "role": self.role.value,
            "content": self.content,
            "image_base64": self.image_base64,
            "tool_result": self.tool_result,
            "tool_calls": (
                [
                    {"name": tc.tool_name, "parameters": tc.parameters, "id": tc.id}
                    for tc in self.tool_calls
                ]
                if self.tool_calls
                else None
            ),
            "tool_call_id": self.tool_call_id,
        }


@dataclass
class ToolCall:
    """
    Structured representation of a parsed tool call from an LLM response.

    This class represents the agent's decision to invoke a specific tool
    with given parameters. It's typically extracted from the LLM's response
    text by a ToolCallParser.

    Attributes:
        tool_name: Name of the tool to invoke (must match a registered tool).
        parameters: Dictionary mapping parameter names to their values for tool execution.

    Example:
        >>> tool_call = ToolCall(
        ...     tool_name="get_weather",
        ...     parameters={"location": "San Francisco", "units": "celsius"}
        ... )
    """

    tool_name: str
    parameters: Dict[str, Any]
    id: Optional[str] = None


@dataclass
class AgentResult:
    """
    Structured result from an agent run.

    Wraps the final assistant response with metadata about which tools were
    called and how many iterations the agent used. Provides backward-compatible
    `content` and `role` properties so existing code that accesses
    ``result.content`` continues to work.

    Attributes:
        message: The final assistant response message.
        tool_name: Name of the last tool called, or None if no tool was used.
        tool_args: Parameters passed to the last tool call.
        iterations: Number of loop iterations used.
        tool_calls: Ordered list of all tool calls made during the run.

    Example:
        >>> result = agent.run([Message(role=Role.USER, content="Search for Python")])
        >>> result.content          # backward-compatible
        'Here are the results...'
        >>> result.tool_name        # structured access
        'search_web'
        >>> result.tool_args
        {'query': 'Python'}
        >>> result.iterations
        2
    """

    message: Message
    tool_name: Optional[str] = None
    tool_args: Dict[str, Any] = field(default_factory=dict)
    iterations: int = 0
    tool_calls: List["ToolCall"] = field(default_factory=list)

    @property
    def content(self) -> str:
        """Backward-compatible access to the final response text."""
        return self.message.content

    @property
    def role(self) -> "Role":
        """Backward-compatible access to the message role."""
        return self.message.role


__all__ = ["Role", "Message", "ToolCall", "AgentResult"]
