"""
Simulation: Research Team
=========================
3 real LLM agents collaborate to research a topic and write a report.

  researcher → analyst → writer → END

Each agent has specialized tools. Tests that:
- Tool calling works across graph nodes
- Context flows correctly between agents
- Final output is coherent and uses all 3 agents' contributions
"""

import os
import sys

# Ensure selectools is importable
sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", "..", "src"))

from selectools import Agent, AgentConfig, AgentGraph, tool
from selectools.providers.openai_provider import OpenAIProvider

# --- Tools ---


@tool(description="Search the web for information on a topic")
def web_search(query: str) -> str:
    """Search the web and return results."""
    # Simulated search results
    results = {
        "ai safety": "Key concerns: alignment, misuse, autonomous systems. Leading researchers: Yoshua Bengio, Stuart Russell.",
        "default": f"Top results for '{query}': Multiple academic papers and industry reports found.",
    }
    for key, val in results.items():
        if key in query.lower():
            return val
    return results["default"]


@tool(description="Analyze data and extract key insights")
def analyze_data(text: str) -> str:
    """Analyze text and return structured insights."""
    word_count = len(text.split())
    return f"Analysis: {word_count} words analyzed. Key themes identified. Sentiment: neutral-positive."


@tool(description="Format text into a structured report")
def format_report(content: str, title: str = "Report") -> str:
    """Format content into a structured report."""
    return f"# {title}\n\n{content}\n\n---\nGenerated by Research Team Pipeline"


def main():
    provider = OpenAIProvider()
    model = "gpt-4.1-mini"

    researcher = Agent(
        provider=provider,
        tools=[web_search],
        config=AgentConfig(
            model=model,
            max_iterations=3,
            system_prompt="You are a research specialist. Use the web_search tool to find information, then summarize your findings clearly.",
        ),
    )

    analyst = Agent(
        provider=provider,
        tools=[analyze_data],
        config=AgentConfig(
            model=model,
            max_iterations=3,
            system_prompt="You are a data analyst. Take the research findings and use the analyze_data tool to extract insights. Provide a clear analysis.",
        ),
    )

    writer = Agent(
        provider=provider,
        tools=[format_report],
        config=AgentConfig(
            model=model,
            max_iterations=3,
            system_prompt="You are a technical writer. Take the analysis and use the format_report tool to create a polished report.",
        ),
    )

    # Build the graph
    graph = AgentGraph.chain(researcher, analyst, writer, names=["researcher", "analyst", "writer"])

    print("Running Research Team simulation...")
    print("=" * 60)
    result = graph.run("Research the current state of AI safety")
    print(f"\n{'=' * 60}")
    print(f"FINAL OUTPUT:\n{result.content[:500]}")
    print(f"\nSteps: {result.steps}")
    print(f"Tokens: {result.total_usage.total_tokens}")
    print(f"Cost: ${result.total_usage.cost_usd:.4f}")
    print(f"Nodes executed: {list(result.node_results.keys())}")

    # Assertions
    assert result.content, "Should produce non-empty output"
    assert result.total_usage.total_tokens > 0, "Should use tokens"
    assert len(result.node_results) == 3, "All 3 agents should execute"
    assert "researcher" in result.node_results
    assert "analyst" in result.node_results
    assert "writer" in result.node_results
    print("\nAll assertions passed!")


if __name__ == "__main__":
    main()
